name: Stage

on:
  pull_request:
    branches: [master]

jobs:
  stagebot:
    name: Run StageBot
    runs-on: ubuntu-latest
    environment:
      name: "stage"
      url: https://vikesec.ca/discord
    concurrency:
      group: "stage"
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Config.py
        run: echo "$BOT_CONFIG" > config.py
        shell: bash
        env:
          BOT_CONFIG: ${{secrets.BOT_CONFIG}}

      - name: Change stage slash commands to have 'z' infront
        run: >
          find . -type f -name "*.py" -not -path '*/\.*' -exec
          sed -i 's/SlashCommandGroup("/SlashCommandGroup("z/g' {} +
        shell: bash

      - name: Build Docker image
        run: docker build -t vikaxe/vikebot:${{ github.sha }} .

      - name: Run StageBot
        run: docker run -e "BOT_TOKEN=$STAGE_TOKEN" -e "BOT_ENV=staging" vikaxe/vikebot 1>/dev/null 2>&1
        shell: bash
        continue-on-error: true
        env:
          STAGE_TOKEN: ${{ secrets.BOT_API_TOKEN }}

      - name: Mark environment as deactivated
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: "stage"
          desc: Stagebot was stopped
